In [1]:
%cd ..
%load_ext autoreload
%autoreload 2


C:\Users\dimitri\workspaces\opensource\finance-toolbox


In [2]:
from fintools.industry_data import *

hfi = load_hfi_returns()
hfi.head()

Convertible Arbitrage  CTA Global  Distressed Securities  \
date                                                                
1997-01                 0.0119      0.0393                 0.0178   
1997-02                 0.0123      0.0298                 0.0122   
1997-03                 0.0078     -0.0021                -0.0012   
1997-04                 0.0086     -0.0170                 0.0030   
1997-05                 0.0156     -0.0015                 0.0233   

         Emerging Markets  Equity Market Neutral  Event Driven  \
date                                                             
1997-01            0.0791                 0.0189        0.0213   
1997-02            0.0525                 0.0101        0.0084   
1997-03           -0.0120                 0.0016       -0.0023   
1997-04            0.0119                 0.0119       -0.0005   
1997-05            0.0315                 0.0189        0.0346   

         Fixed Income Arbitrage  Global Macro  Long/Short Equity  \
date                                                               
1997-01                  0.0191        0.0573             0.0281   
1997-02                  0.0122        0.0175            -0.0006   
1997-03                  0.0109       -0.0119            -0.0084   
1997-04                  0.0130        0.0172             0.0084   
1997-05                  0.0118        0.0108             0.0394   

         Merger Arbitrage  Relative Value  Short Selling  Funds Of Funds  
date                                                                      
1997-01            0.0150          0.0180        -0.0166          0.0317  
1997-02            0.0034          0.0118         0.0426          0.0106  
1997-03            0.0060          0.0010         0.0778         -0.0077  
1997-04           -0.0001          0.0122        -0.0129          0.0009  
1997-05            0.0197          0.0173        -0.0737          0.0275

### Skewness
$$ S(R) = \frac{E[(R-E(R))^3]}{\sigma_R^3} $$

In [3]:
hfi.skew().sort_values()

Fixed Income Arbitrage   -3.962959
Convertible Arbitrage    -2.654757
Equity Market Neutral    -2.136641
Relative Value           -1.825900
Event Driven             -1.417250
Merger Arbitrage         -1.327668
Distressed Securities    -1.308316
Emerging Markets         -1.173773
Long/Short Equity        -0.392469
Funds Of Funds           -0.363862
CTA Global                0.174697
Short Selling             0.772387
Global Macro              0.988569
dtype: float64

In [5]:
import scipy.stats
import numpy as np

np.sort(scipy.stats.skew(hfi))


array([-3.94032029, -2.63959223, -2.12443538, -1.81546975, -1.40915356,
       -1.32008333, -1.30084204, -1.16706749, -0.39022677, -0.36178308,
        0.17369864,  0.76797484,  0.98292188])

In [6]:
np.sort(scipy.stats.skew(hfi, bias=False))

array([-3.96295862, -2.65475748, -2.13664091, -1.82590017, -1.41724958,
       -1.32766761, -1.30831577, -1.17377265, -0.39246874, -0.36386164,
        0.1746966 ,  0.77238709,  0.98856907])

### Kurtosis
$$ K(R) = \frac{E[(R-E(R)^4]}{\sigma_R^4} $$

In [7]:
hfi.kurt().sort_values()

CTA Global                -0.024781
Long/Short Equity          1.576431
Global Macro               2.817691
Short Selling              3.201032
Funds Of Funds             4.171770
Distressed Securities      5.007403
Event Driven               5.156059
Merger Arbitrage           5.872733
Emerging Markets           6.394438
Relative Value             9.320184
Equity Market Neutral     14.515783
Convertible Arbitrage     20.694912
Fixed Income Arbitrage    27.382747
dtype: float64

In [8]:
np.sort(scipy.stats.kurtosis(hfi, bias=True))

array([-0.04703963,  1.52389258,  2.74167945,  3.11777175,  4.07015278,
        4.88998336,  5.03582817,  5.73894979,  6.25078841,  9.12120787,
       14.21855526, 20.28083446, 26.84219928])